name: mini_notes
display-name: Mini Notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  provider: ^6.1.1
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  popover: ^0.3.0
  vibration: ^1.8.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/image/mate.png"
flutter:
  uses-material-design: true

  assets:
  - assets/image/
  - lib/image/
